# ATENÇÃO: os credentials são sempre *encriptados*, esse arquivo é apenas um exemplo de visualização
# Aqui normalmente ficam as informações dos servers, mailers, oauths, basicamente tudo que for sensível.
# Para criar o seu credentials, use o comando `EDITOR=nano rails credentials:edit`

default_server_config: &default_server_config
  new_relic_access_token: "NEW-RELIC-ACCESS-TOKEN"
  sentry_access_token: "SENTRY-ACCESS-TOKEN"
  aws_s3:
    bucket_name: "BUCKET-ID"
    access_key_id: "ACCESS-KEY-ID"
    secret_access_key: "SECRET-ACCESS-KEY"
    region: "REGION-ID"
  facebook_oauth2:
    app_id: "APP-ID"
    app_secret: "APP-SECRET"
  google_oauth2:
    web:
      client_id: "WEB-CLIENT-ID"
      client_secret: "WEB-CLIENT-SECRET"
      redirect_uri: "WEB-REDIRECT-URI"
    ios:
      client_id: "IOS-CLIENT-ID"
      client_secret: "IOS-CLIENT-SECRET"
      redirect_uri: "IOS-REDIRECT-URI"
    android:
      client_id: "ANDROID-CLIENT-ID"
      client_secret: "ANDROID-CLIENT-SECRET"
      redirect_uri: "ANDROID-REDIRECT-URI"
  apple_oauth2:
    client_id: "APPLE-CLIENT-ID"

development:
  <<: *default_server_config

test:
  <<: *default_server_config

staging:
  rails_admin:
    username: api_template
    password: secret123
  <<: *default_server_config

production:
  rails_admin:
    username: api_template
    # Para gerar uma senha aleatória utilize o site:
    # https://privacycanada.net/strong-password-generator
    password: cole-a-senha-aqui
  <<: *default_server_config

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: # A secret_key_base é gerada automaticamente quando o credentials é criado e é única por projeto
